# markpost 配置文件

# title 的最大字节数，可以不设置
TITLE_MAX_SIZE = 5

# body 的最大字节数，可以不设置  
BODY_MAX_SIZE = 1048576

# 接口限流频率，每分钟允许请求次数，可以不设置
API_RATE_LIMIT = 60

# GitHub OAuth2 配置
[github]
client_id = "your_github_client_id"
client_secret = "your_github_client_secret"
redirect_url = "http://localhost:8080/auth/github/callback"

# JWT 配置
[jwt]
secret_key = "your_jwt_secret_key"
access_token_expire = "24h"
refresh_token_expire = "720h"      # 30 days
