services:
  markpost:
    build: .
    container_name: markpost-app
    ports:
      - "8080:8080"
    volumes:
      # 挂载数据目录，持久化数据库文件
      - ./data:/app/data
      # 挂载配置文件（可选，如果需要动态修改配置）
      - ./markpost.toml:/app/markpost.toml:ro
    environment:
      - GIN_MODE=release
    restart: unless-stopped
