linters:
  enable:
    - errcheck
    - gosimple
    - staticcheck
    - unused
    - ineffassign
    - govet
    - revive
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable-all: true
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
  goimports:
    local-prefixes: markpost

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosimple
        - revive
    - path: cmd/
      linters:
        - revive

run:
  timeout: 5m
  skip-dirs:
    - docs
    - tools
