// Package main implements the CSS build helper.
//
// It extracts the inline <style> block from templates/post.html, minifies it
// with tdewolff/minify, content-addresses the result with xxhash64, writes the
// fingerprinted asset to static/post.<hash>.css, and generates
// internal/web/csshash.go (which go:embeds the asset and exposes CSSHash) so the
// template can reference /static/post.<hash>.css and the handler can serve the
// embedded bytes with a one-year immutable Cache-Control.
//
// Invoke via `go generate ./internal/web` from the backend module root.
package main

import (
	"bytes"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/cespare/xxhash/v2"
	"github.com/tdewolff/minify/v2"
	mincss "github.com/tdewolff/minify/v2/css"
)

const (
	moduleRootNote = "run from the backend module root: go generate ./internal/web"
)

func die(format string, args ...any) {
	log.Fatalf("buildcss: "+format, args...)
}

func main() {
	root, err := findModuleRoot()
	if err != nil {
		die("%v (%s)", err, moduleRootNote)
	}

	cssPath := filepath.Join(root, "templates", "post.css")
	cssSource, err := os.ReadFile(cssPath)
	if err != nil {
		die("read css source %s: %v", cssPath, err)
	}

	minified, err := minifyCSS(strings.TrimSpace(string(cssSource)))
	if err != nil {
		die("minify css: %v", err)
	}

	hash := fmt.Sprintf("%016x", xxhash.Sum64String(string(minified)))

	webDir := filepath.Join(root, "internal", "web")
	if err := os.MkdirAll(webDir, 0o755); err != nil {
		die("create web dir: %v", err)
	}
	cssFile := filepath.Join(webDir, "post."+hash+".css")
	if err := os.WriteFile(cssFile, minified, 0o644); err != nil {
		die("write css asset: %v", err)
	}

	if err := writeCSSHashGo(webDir, hash); err != nil {
		die("write csshash.go: %v", err)
	}

	rel, _ := filepath.Rel(root, cssFile)
	fmt.Printf("buildcss: wrote %s (%d bytes, hash %s)\n", filepath.ToSlash(rel), len(minified), hash)
}

func minifyCSS(css string) ([]byte, error) {
	m := minify.New()
	m.AddFunc("text/css", mincss.Minify)
	var buf bytes.Buffer
	if err := m.Minify("text/css", &buf, strings.NewReader(css)); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func findModuleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not locate go.mod walking up from %s", dir)
		}
		dir = parent
	}
}

func writeCSSHashGo(webDir, hash string) error {
	cssFile := "post." + hash + ".css"
	content := fmt.Sprintf(`// Code generated by buildcss; DO NOT EDIT.

// Package web exposes build-time, content-addressed static assets and build
// metadata for the rendered HTML shell. The CSS asset is minified at build
// time (see cmd/buildcss), go:embedded into the binary, and served at a
// content-hashed URL so it can be cached with Cache-Control: immutable.
package web

import _ "embed"

// CSSHash is the xxhash64 of the minified CSS, used in the asset URL
// (/static/post.<CSSHash>.css) for cache busting.
var CSSHash = %q

//go:embed %s
var cssBytes []byte

// CSSBytes returns the minified CSS asset bytes.
func CSSBytes() []byte { return cssBytes }
`, hash, cssFile)

	return os.WriteFile(filepath.Join(webDir, "csshash.go"), []byte(content), 0o644)
}
