---
all:
  children:
    dev:
      hosts:
        fn:
          ansible_user: fn
          ansible_host: 192.168.5.200

    staging:
      hosts:
        oect:
          ansible_user: alice
          ansible_host: 192.168.5.50

    production:
      hosts:
        ttyo:
          ansible_user: alice
          ansible_host: 43.133.160.29
