// Code generated by buildcss; DO NOT EDIT.

// Package web exposes build-time, content-addressed static assets and build
// metadata for the rendered HTML shell. The CSS asset is minified at build
// time (see cmd/buildcss), go:embedded into the binary, and served at a
// content-hashed URL so it can be cached with Cache-Control: immutable.
package web

import _ "embed"

// CSSHash is the xxhash64 of the minified CSS, used in the asset URL
// (/static/post.<CSSHash>.css) for cache busting.
var CSSHash = "8957c7305ed33f00"

//go:embed post.8957c7305ed33f00.css
var cssBytes []byte

// CSSBytes returns the minified CSS asset bytes.
func CSSBytes() []byte { return cssBytes }
